
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.8

[window.padding]
x = 8  # Example: 10 pixels of horizontal padding
y = 8  # Example: 10 pixels of vertical padding

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"
